import type { Metadata } from 'next';

import { Geist, Geist_Mono, Inter, Inter_Tight } from 'next/font/google';

import './globals.css';
import 'streamdown/styles.css';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const interTight = Inter_Tight({
  subsets: ['latin'],
  variable: '--font-heading',
});

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={cn('font-sans', inter.variable, interTight.variable)}
      lang="pt-BR"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <Providers>{children}</Providers>
        </NuqsAdapter>

        <Toaster />
      </body>
    </html>
  );
}
