/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * training-manager API
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';

export type GetApiStats200 = {
  completedWorkoutsCount: number;
  conclusionRate: number;
  consistencyByDay: GetApiStats200ConsistencyByDay;
  totalTimeInSeconds: number;
  workoutStreak: number;
};

export type GetApiStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetApiStats401 = {
  code: string;
  error: string;
};

export type GetApiStats404 = {
  code: string;
  error: string;
};

export type GetApiStats500 = {
  code: string;
  error: string;
};

export type GetApiStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId?: string;
  consistencyByDay: GetHomeData200ConsistencyByDay;
  /** @nullable */
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = null | {
  /** @nullable */
  coverImageUrl?: null | string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRest: boolean;
  name: string;
  weekDay:
    | 'FRIDAY'
    | 'MONDAY'
    | 'SATURDAY'
    | 'SUNDAY'
    | 'THURSDAY'
    | 'TUESDAY'
    | 'WEDNESDAY';
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
};

export type GetHomeData401 = {
  code: string;
  error: string;
};

export type GetHomeData404 = {
  code: string;
  error: string;
};

export type GetHomeData500 = {
  code: string;
  error: string;
};

export type GetUser200 = {
  /**
   * Idade do usuário
   * @exclusiveMinimum 0
   */
  age: number;
  /**
   * Percentual de gordura corporal (0 a 1000). Ex.: 40% = 400; 37,5% = 375
   * @minimum 0
   * @maximum 1000
   */
  bodyFatPercentage: number;
  /**
   * Altura do usuário em centímetros. Ex.: 1.70m = 170
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /** ID do usuário */
  id: string;
  /**
   * Link da foto de perfil do usuário
   * @nullable
   */
  image: null | string;
  /**
   * None do usuário
   * @minLength 1
   */
  name: string;
  /**
   * Peso do usuário em gramas. Ex.: 70kg = 70000
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
};

export type GetUser401 = {
  code: string;
  error: string;
};

export type GetUser404 = {
  code: string;
  error: string;
};

export type GetUser500 = {
  code: string;
  error: string;
};

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export type GetWorkoutPlansParams = {
  isActive?: boolean;
};

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
};

export type GetWorkoutPlans401 = {
  code: string;
  error: string;
};

export type GetWorkoutPlans500 = {
  code: string;
  error: string;
};

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export type CreateWorkoutPlanBody = {
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl?: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
  /** Se é dia de descanso (true) ou treino (false) */
  isRest?: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
};

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
};

export type CreateWorkoutPlan400 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan401 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan404 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan500 = {
  code: string;
  error: string;
};

/**
 * Dia da semana
 */
export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  userId: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan200WorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
};

export type GetWorkoutPlan401 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan404 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan500 = {
  code: string;
  error: string;
};

export const GetWorkoutDay200WeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type aiResponse = aiResponseSuccess;

/**
 * @summary Chat with AI personal trainer
 */
export type aiResponse200 = {
  data: void;
  status: 200;
};

export type aiResponseSuccess = aiResponse200 & {
  headers: Headers;
};

export type CompleteWorkoutSession200 = {
  /**
   * Momento de conclusão da sessão (null enquanto em andamento)
   * @nullable
   */
  completedAt: null | string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Momento de início da sessão */
  startedAt: string;
};

export type CompleteWorkoutSession401 = {
  code: string;
  error: string;
};

export type CompleteWorkoutSession404 = {
  code: string;
  error: string;
};

export type CompleteWorkoutSession500 = {
  code: string;
  error: string;
};

export type GetWorkoutDay200 = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: GetWorkoutDay200ExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /**
   * Sessão atual do dia (null quando não iniciada)
   * @nullable
   */
  session: GetWorkoutDay200Session;
  /** Dia da semana */
  weekDay: GetWorkoutDay200WeekDay;
};

/**
 * Sessão atual do dia (null quando não iniciada)
 * @nullable
 */
export type GetWorkoutDay200Session = {
  /**
   * Momento de conclusão da sessão (null enquanto em andamento)
   * @nullable
   */
  completedAt: null | string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Momento de início da sessão */
  startedAt: string;
} | null;

export type GetWorkoutDay401 = {
  code: string;
  error: string;
};

export type GetWorkoutDay404 = {
  code: string;
  error: string;
};

export type GetWorkoutDay500 = {
  code: string;
  error: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
};

export type StartWorkoutSession401 = {
  code: string;
  error: string;
};

export type StartWorkoutSession404 = {
  code: string;
  error: string;
};

export type StartWorkoutSession409 = {
  code: string;
  error: string;
};

export type StartWorkoutSession422 = {
  code: string;
  error: string;
};
export type StartWorkoutSession500 = {
  code: string;
  error: string;
};

export const getAiUrl = () => {
  return `/api/ai/`;
};

export const ai = async (options?: RequestInit): Promise<aiResponse> => {
  return customFetch<aiResponse>(getAiUrl(), {
    ...options,
    method: 'POST',
  });
};

export type getHomeDataResponse =
  | getHomeDataResponseError
  | getHomeDataResponseSuccess;

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};

export const getGetHomeDataUrl = () => {
  return `/api/home/`;
};

export const getHomeData = async (
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(), {
    ...options,
    method: 'GET',
  });
};

export type getUserResponse = getUserResponseError | getUserResponseSuccess;

/**
 * @summary Get user
 */
export type getUserResponse200 = {
  data: GetUser200;
  status: 200;
};

export type getUserResponse401 = {
  data: GetUser401;
  status: 401;
};

export type getUserResponse404 = {
  data: GetUser404;
  status: 404;
};

export type getUserResponse500 = {
  data: GetUser500;
  status: 500;
};
export type getUserResponseError = (
  | getUserResponse401
  | getUserResponse404
  | getUserResponse500
) & {
  headers: Headers;
};

export type getUserResponseSuccess = getUserResponse200 & {
  headers: Headers;
};

export const getGetUserUrl = () => {
  return `/api/me/`;
};

export const getUser = async (
  options?: RequestInit,
): Promise<getUserResponse> => {
  return customFetch<getUserResponse>(getGetUserUrl(), {
    ...options,
    method: 'GET',
  });
};

export type getApiStatsResponse =
  | getApiStatsResponseError
  | getApiStatsResponseSuccess;

/**
 * @summary Get user workout stats
 */
export type getApiStatsResponse200 = {
  data: GetApiStats200;
  status: 200;
};

export type getApiStatsResponse401 = {
  data: GetApiStats401;
  status: 401;
};

export type getApiStatsResponse404 = {
  data: GetApiStats404;
  status: 404;
};

export type getApiStatsResponse500 = {
  data: GetApiStats500;
  status: 500;
};
export type getApiStatsResponseError = (
  | getApiStatsResponse401
  | getApiStatsResponse404
  | getApiStatsResponse500
) & {
  headers: Headers;
};

export type getApiStatsResponseSuccess = getApiStatsResponse200 & {
  headers: Headers;
};

export const getGetApiStatsUrl = (params: GetApiStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/stats/?${stringifiedParams}`
    : `/api/stats/`;
};

export const getApiStats = async (
  params: GetApiStatsParams,
  options?: RequestInit,
): Promise<getApiStatsResponse> => {
  return customFetch<getApiStatsResponse>(getGetApiStatsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type getWorkoutPlansResponse =
  | getWorkoutPlansResponseError
  | getWorkoutPlansResponseSuccess;

/**
 * @summary List workout plans
 */
export type getWorkoutPlansResponse200 = {
  data: GetWorkoutPlans200Item[];
  status: 200;
};

export type getWorkoutPlansResponse401 = {
  data: GetWorkoutPlans401;
  status: 401;
};

export type getWorkoutPlansResponse500 = {
  data: GetWorkoutPlans500;
  status: 500;
};
export type getWorkoutPlansResponseError = (
  | getWorkoutPlansResponse401
  | getWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlansResponseSuccess = getWorkoutPlansResponse200 & {
  headers: Headers;
};

export const getGetWorkoutPlansUrl = (params?: GetWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/workout-plans/?${stringifiedParams}`
    : `/api/workout-plans/`;
};

export const getWorkoutPlans = async (
  params?: GetWorkoutPlansParams,
  options?: RequestInit,
): Promise<getWorkoutPlansResponse> => {
  return customFetch<getWorkoutPlansResponse>(getGetWorkoutPlansUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseError
  | createWorkoutPlanResponseSuccess;

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};

export const getCreateWorkoutPlanUrl = () => {
  return `/api/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    body: JSON.stringify(createWorkoutPlanBody),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'POST',
  });
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseError
  | getWorkoutPlanResponseSuccess;

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/api/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseError
  | getWorkoutDayResponseSuccess;

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseError
  | startWorkoutSessionResponseSuccess;

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: 'POST',
    },
  );
};

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseError
  | completeWorkoutSessionResponseSuccess;

/**
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200;
  status: 200;
};

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401;
  status: 401;
};

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404;
  status: 404;
};

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500;
  status: 500;
};
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers;
  };

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}/complete`;
};

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  options?: RequestInit,
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};
