import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * training-manager API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';

import type { BodyType, ErrorType } from '../../axios';

import { customInstance } from '../../axios';

export type CreateAvatarUploadUrl200 = {
  /**
   * Validade da URL assinada, em segundos
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  expiresIn: number;
  /** Chave do objeto no bucket; deve ser reenviada em PUT /me/image para concluir a troca da foto */
  key: string;
  /** URL assinada para envio direto da imagem ao storage, sem passar pela API */
  uploadUrl: string;
};

export type CreateAvatarUploadUrl400 = {
  code: string;
  error: string;
};

export type CreateAvatarUploadUrl401 = {
  code: string;
  error: string;
};

export type CreateAvatarUploadUrl500 = {
  code: string;
  error: string;
};

export type CreateAvatarUploadUrlBody = {
  /**
   * Tamanho em bytes da imagem já recortada que será enviada. Serve apenas como triagem inicial: o tamanho real é verificado no objeto enviado durante o commit, então este valor não é tratado como garantia.
   * @minimum 1
   * @maximum 2097152
   */
  contentLength: number;
};

export type GetApiStats200 = {
  /** Quantidade de sessões de treino concluídas no período. */
  completedWorkoutsCount: number;
  /** Proporção entre 0 e 1 das sessões iniciadas no período que foram concluídas. */
  conclusionRate: number;
  /** Dias do período com ao menos uma sessão, indexados pela data (YYYY-MM-DD). Dias sem sessão são omitidos. */
  consistencyByDay: GetApiStats200ConsistencyByDay;
  /** Soma da duração das sessões concluídas no período. */
  totalTimeInSeconds: number;
  /** Sequência atual, em dias, de treinos concluídos nos dias agendados. Não se limita ao período consultado. */
  workoutStreak: number;
  /** Maior sequência, em dias, já alcançada pelo usuário. Não se limita ao período consultado. */
  workoutStreakRecord: number;
};

/**
 * Dias do período com ao menos uma sessão, indexados pela data (YYYY-MM-DD). Dias sem sessão são omitidos.
 */
export type GetApiStats200ConsistencyByDay = {
  [key: string]: {
    /** Pelo menos uma sessão iniciada neste dia foi concluída. */
    workoutDayCompleted: boolean;
    /** Pelo menos uma sessão foi iniciada neste dia. */
    workoutDayStarted: boolean;
  };
};

export type GetApiStats401 = {
  code: string;
  error: string;
};

export type GetApiStats404 = {
  code: string;
  error: string;
};

export type GetApiStats500 = {
  code: string;
  error: string;
};

export type GetApiStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId?: string;
  consistencyByDay: GetHomeData200ConsistencyByDay;
  /** @nullable */
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = null | {
  /** @nullable */
  coverImageUrl?: null | string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  isRest: boolean;
  name: string;
  weekDay:
    | 'FRIDAY'
    | 'MONDAY'
    | 'SATURDAY'
    | 'SUNDAY'
    | 'THURSDAY'
    | 'TUESDAY'
    | 'WEDNESDAY';
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
};

export type GetHomeData401 = {
  code: string;
  error: string;
};

export type GetHomeData404 = {
  code: string;
  error: string;
};

export type GetHomeData500 = {
  code: string;
  error: string;
};

export type GetUser200 = {
  /**
   * Idade do usuário
   * @exclusiveMinimum 0
   */
  age: number;
  /**
   * Percentual de gordura corporal (0 a 1000). Ex.: 40% = 400; 37,5% = 375
   * @minimum 0
   * @maximum 1000
   */
  bodyFatPercentage: number;
  /**
   * Altura do usuário em centímetros. Ex.: 1.70m = 170
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /** ID do usuário */
  id: string;
  /**
   * Link da foto de perfil do usuário
   * @nullable
   */
  image: null | string;
  /**
   * None do usuário
   * @minLength 1
   */
  name: string;
  /**
   * Peso do usuário em gramas. Ex.: 70kg = 70000
   * @minimum 1
   * @maximum 9007199254740991
   */
  weightInGrams: number;
};

export type GetUser401 = {
  code: string;
  error: string;
};

export type GetUser404 = {
  code: string;
  error: string;
};

export type GetUser500 = {
  code: string;
  error: string;
};

export type GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type GetWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export type GetWorkoutPlansParams = {
  isActive?: boolean;
};

export type RemoveUserImage401 = {
  code: string;
  error: string;
};

export type RemoveUserImage500 = {
  code: string;
  error: string;
};

export type UpdateUserImage200 = {
  /** URL pública da nova foto de perfil do usuário */
  image: string;
};

export type UpdateUserImage400 = {
  code: string;
  error: string;
};

export type UpdateUserImage401 = {
  code: string;
  error: string;
};

export type UpdateUserImage404 = {
  code: string;
  error: string;
};

export type UpdateUserImage413 = {
  code: string;
  error: string;
};

export type UpdateUserImage500 = {
  code: string;
  error: string;
};

export type UpdateUserImageBody = {
  /**
   * Chave do objeto retornada por POST /me/image/upload-url. O servidor valida que a chave pertence ao usuário autenticado e inspeciona o objeto no storage antes de vinculá-lo ao perfil.
   * @minLength 1
   */
  key: string;
};

export const GetWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export type GetWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: GetWorkoutPlans200ItemWorkoutDaysItem[];
};

export type GetWorkoutPlans200ItemWorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: GetWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: GetWorkoutPlans200ItemWorkoutDaysItemWeekDay;
};

export type GetWorkoutPlans401 = {
  code: string;
  error: string;
};

export type GetWorkoutPlans500 = {
  code: string;
  error: string;
};

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export type CreateWorkoutPlanBody = {
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl?: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
  /** Se é dia de descanso (true) ou treino (false) */
  isRest?: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
};

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  /** Lista com exatamente 7 dias de treino (segunda a domingo) */
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
};

export type CreateWorkoutPlan400 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan401 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan404 = {
  code: string;
  error: string;
};

export type CreateWorkoutPlan500 = {
  code: string;
  error: string;
};

/**
 * Dia da semana
 */
export type GetActiveWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetActiveWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetActiveWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetActiveWorkoutPlan200WorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type GetActiveWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  userId: string;
  workoutDays: GetActiveWorkoutPlan200WorkoutDaysItem[];
};

export type GetActiveWorkoutPlan200WorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: GetActiveWorkoutPlan200WorkoutDaysItemWeekDay;
};

export type GetActiveWorkoutPlan401 = {
  code: string;
  error: string;
};

export type GetActiveWorkoutPlan404 = {
  code: string;
  error: string;
};

export type GetActiveWorkoutPlan500 = {
  code: string;
  error: string;
};

/**
 * Dia da semana
 */
export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do exercício
   * @minLength 1
   */
  name: string;
  /**
   * Ordem do exercício no dia
   * @minimum 0
   */
  order: number;
  /**
   * Número de repetições
   * @minimum 1
   */
  reps: number;
  /**
   * Tempo de descanso entre séries em segundos
   * @minimum 1
   */
  restTimeInSeconds: number;
  /**
   * Número de séries
   * @minimum 1
   */
  sets: number;
};

/**
 * Dia da semana
 */
export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * Nome do plano de treino
   * @minLength 1
   */
  name: string;
  userId: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan200WorkoutDaysItem = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  exercisesCount: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Dia da semana */
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
};

export type GetWorkoutPlan401 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan404 = {
  code: string;
  error: string;
};

export type GetWorkoutPlan500 = {
  code: string;
  error: string;
};

export const GetWorkoutDay200WeekDay = {
  FRIDAY: 'FRIDAY',
  MONDAY: 'MONDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
  THURSDAY: 'THURSDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
} as const;

export type CompleteWorkoutSession200 = {
  /**
   * Momento de conclusão da sessão (null enquanto em andamento)
   * @nullable
   */
  completedAt: null | string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Momento de início da sessão */
  startedAt: string;
};

export type CompleteWorkoutSession401 = {
  code: string;
  error: string;
};

export type CompleteWorkoutSession404 = {
  code: string;
  error: string;
};

export type CompleteWorkoutSession500 = {
  code: string;
  error: string;
};

export type GetWorkoutDay200 = {
  /**
   * URL da imagem de capa do dia de treino. Usar as URLs de superior ou inferior conforme o foco muscular do dia.
   * @nullable
   */
  coverImageUrl: null | string;
  /**
   * Duração estimada em segundos (0 para dias de descanso)
   * @minimum 0
   */
  estimatedDurationInSeconds: number;
  /** Lista de exercícios do dia (vazia para dias de descanso) */
  exercises: GetWorkoutDay200ExercisesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Se é dia de descanso (true) ou treino (false) */
  isRest: boolean;
  /**
   * Nome do dia (ex.: Peito e Tríceps, Costas e Bíceps, Descanso)
   * @minLength 1
   */
  name: string;
  /** Sessão atual do dia (null quando não iniciada) */
  session?: GetWorkoutDay200Session;
  /** Dia da semana */
  weekDay: GetWorkoutDay200WeekDay;
};

/**
 * Sessão atual do dia (null quando não iniciada)
 */
export type GetWorkoutDay200Session = {
  /**
   * Momento de conclusão da sessão (null enquanto em andamento)
   * @nullable
   */
  completedAt: null | string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** Momento de início da sessão */
  startedAt: string;
};

export type GetWorkoutDay401 = {
  code: string;
  error: string;
};

export type GetWorkoutDay404 = {
  code: string;
  error: string;
};

export type GetWorkoutDay500 = {
  code: string;
  error: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
};

export type StartWorkoutSession401 = {
  code: string;
  error: string;
};

export type StartWorkoutSession404 = {
  code: string;
  error: string;
};

export type StartWorkoutSession409 = {
  code: string;
  error: string;
};

export type StartWorkoutSession422 = {
  code: string;
  error: string;
};

export type StartWorkoutSession500 = {
  code: string;
  error: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Chat with AI personal trainer
 */
export const ai = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { method: 'POST', signal, url: `/api/ai/` },
    options,
  );
};

export const getAiMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ai>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ai>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['ai'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ai>>,
    void
  > = () => {
    return ai(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AiMutationError = ErrorType<unknown>;

export type AiMutationResult = NonNullable<Awaited<ReturnType<typeof ai>>>;

/**
 * @summary Chat with AI personal trainer
 */
export const useAi = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ai>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof ai>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getAiMutationOptions(options), queryClient);
};

/**
 * @summary Get home page data
 */
export const getHomeData = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetHomeData200>(
    { method: 'GET', signal, url: `/api/home/` },
    options,
  );
};

export const getGetHomeDataQueryKey = () => {
  return [`/api/home/`] as const;
};

export const getGetHomeDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = ErrorType<GetHomeData401 | GetHomeData404 | GetHomeData500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHomeDataQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHomeData>>> = ({
    signal,
  }) => getHomeData(requestOptions, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHomeData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHomeDataQueryError = ErrorType<
  GetHomeData401 | GetHomeData404 | GetHomeData500
>;
export type GetHomeDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHomeData>>
>;

export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = ErrorType<GetHomeData401 | GetHomeData404 | GetHomeData500>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHomeData>>,
          TError,
          Awaited<ReturnType<typeof getHomeData>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = ErrorType<GetHomeData401 | GetHomeData404 | GetHomeData500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHomeData>>,
          TError,
          Awaited<ReturnType<typeof getHomeData>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = ErrorType<GetHomeData401 | GetHomeData404 | GetHomeData500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get home page data
 */
export function useGetHomeData<
  TData = Awaited<ReturnType<typeof getHomeData>>,
  TError = ErrorType<GetHomeData401 | GetHomeData404 | GetHomeData500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHomeData>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHomeDataQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get user
 */
export const getUser = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetUser200>(
    { method: 'GET', signal, url: `/api/me/` },
    options,
  );
};

export const getGetUserQueryKey = () => {
  return [`/api/me/`] as const;
};

export const getGetUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<GetUser401 | GetUser404 | GetUser500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({
    signal,
  }) => getUser(requestOptions, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserQueryError = ErrorType<GetUser401 | GetUser404 | GetUser500>;
export type GetUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUser>>
>;

export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<GetUser401 | GetUser404 | GetUser500>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<GetUser401 | GetUser404 | GetUser500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<GetUser401 | GetUser404 | GetUser500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user
 */
export function useGetUser<
  TData = Awaited<ReturnType<typeof getUser>>,
  TError = ErrorType<GetUser401 | GetUser404 | GetUser500>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a presigned URL for uploading a profile photo
 */
export const createAvatarUploadUrl = (
  createAvatarUploadUrlBody: BodyType<CreateAvatarUploadUrlBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateAvatarUploadUrl200>(
    {
      data: createAvatarUploadUrlBody,
      headers: { 'Content-Type': 'application/json' },
      method: 'POST',
      signal,
      url: `/api/me/image/upload-url`,
    },
    options,
  );
};

export const getCreateAvatarUploadUrlMutationOptions = <
  TError = ErrorType<
    | CreateAvatarUploadUrl400
    | CreateAvatarUploadUrl401
    | CreateAvatarUploadUrl500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAvatarUploadUrl>>,
    TError,
    { data: BodyType<CreateAvatarUploadUrlBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAvatarUploadUrl>>,
  TError,
  { data: BodyType<CreateAvatarUploadUrlBody> },
  TContext
> => {
  const mutationKey = ['createAvatarUploadUrl'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAvatarUploadUrl>>,
    { data: BodyType<CreateAvatarUploadUrlBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createAvatarUploadUrl(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAvatarUploadUrlMutationBody =
  BodyType<CreateAvatarUploadUrlBody>;
export type CreateAvatarUploadUrlMutationError = ErrorType<
  CreateAvatarUploadUrl400 | CreateAvatarUploadUrl401 | CreateAvatarUploadUrl500
>;
export type CreateAvatarUploadUrlMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAvatarUploadUrl>>
>;

/**
 * @summary Create a presigned URL for uploading a profile photo
 */
export const useCreateAvatarUploadUrl = <
  TError = ErrorType<
    | CreateAvatarUploadUrl400
    | CreateAvatarUploadUrl401
    | CreateAvatarUploadUrl500
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAvatarUploadUrl>>,
      TError,
      { data: BodyType<CreateAvatarUploadUrlBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAvatarUploadUrl>>,
  TError,
  { data: BodyType<CreateAvatarUploadUrlBody> },
  TContext
> => {
  return useMutation(
    getCreateAvatarUploadUrlMutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Commit an uploaded profile photo
 */
export const updateUserImage = (
  updateUserImageBody: BodyType<UpdateUserImageBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UpdateUserImage200>(
    {
      data: updateUserImageBody,
      headers: { 'Content-Type': 'application/json' },
      method: 'PUT',
      signal,
      url: `/api/me/image`,
    },
    options,
  );
};

export const getUpdateUserImageMutationOptions = <
  TError = ErrorType<
    | UpdateUserImage400
    | UpdateUserImage401
    | UpdateUserImage404
    | UpdateUserImage413
    | UpdateUserImage500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserImage>>,
    TError,
    { data: BodyType<UpdateUserImageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserImage>>,
  TError,
  { data: BodyType<UpdateUserImageBody> },
  TContext
> => {
  const mutationKey = ['updateUserImage'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserImage>>,
    { data: BodyType<UpdateUserImageBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateUserImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserImageMutationBody = BodyType<UpdateUserImageBody>;
export type UpdateUserImageMutationError = ErrorType<
  | UpdateUserImage400
  | UpdateUserImage401
  | UpdateUserImage404
  | UpdateUserImage413
  | UpdateUserImage500
>;
export type UpdateUserImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserImage>>
>;

/**
 * @summary Commit an uploaded profile photo
 */
export const useUpdateUserImage = <
  TError = ErrorType<
    | UpdateUserImage400
    | UpdateUserImage401
    | UpdateUserImage404
    | UpdateUserImage413
    | UpdateUserImage500
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserImage>>,
      TError,
      { data: BodyType<UpdateUserImageBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserImage>>,
  TError,
  { data: BodyType<UpdateUserImageBody> },
  TContext
> => {
  return useMutation(getUpdateUserImageMutationOptions(options), queryClient);
};

/**
 * @summary Remove the profile photo
 */
export const removeUserImage = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { method: 'DELETE', signal, url: `/api/me/image` },
    options,
  );
};

export const getRemoveUserImageMutationOptions = <
  TError = ErrorType<RemoveUserImage401 | RemoveUserImage500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeUserImage>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeUserImage>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['removeUserImage'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeUserImage>>,
    void
  > = () => {
    return removeUserImage(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveUserImageMutationError = ErrorType<
  RemoveUserImage401 | RemoveUserImage500
>;

export type RemoveUserImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeUserImage>>
>;

/**
 * @summary Remove the profile photo
 */
export const useRemoveUserImage = <
  TError = ErrorType<RemoveUserImage401 | RemoveUserImage500>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeUserImage>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeUserImage>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRemoveUserImageMutationOptions(options), queryClient);
};

/**
 * @summary Get user workout stats
 */
export const getApiStats = (
  params: GetApiStatsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetApiStats200>(
    { method: 'GET', params, signal, url: `/api/stats/` },
    options,
  );
};

export const getGetApiStatsQueryKey = (params?: GetApiStatsParams) => {
  return [`/api/stats/`, ...(params ? [params] : [])] as const;
};

export const getGetApiStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = ErrorType<GetApiStats401 | GetApiStats404 | GetApiStats500>,
>(
  params: GetApiStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiStatsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiStats>>> = ({
    signal,
  }) => getApiStats(params, requestOptions, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiStatsQueryError = ErrorType<
  GetApiStats401 | GetApiStats404 | GetApiStats500
>;
export type GetApiStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiStats>>
>;

export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = ErrorType<GetApiStats401 | GetApiStats404 | GetApiStats500>,
>(
  params: GetApiStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiStats>>,
          TError,
          Awaited<ReturnType<typeof getApiStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = ErrorType<GetApiStats401 | GetApiStats404 | GetApiStats500>,
>(
  params: GetApiStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiStats>>,
          TError,
          Awaited<ReturnType<typeof getApiStats>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = ErrorType<GetApiStats401 | GetApiStats404 | GetApiStats500>,
>(
  params: GetApiStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user workout stats
 */
export function useGetApiStats<
  TData = Awaited<ReturnType<typeof getApiStats>>,
  TError = ErrorType<GetApiStats401 | GetApiStats404 | GetApiStats500>,
>(
  params: GetApiStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiStatsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List workout plans
 */
export const getWorkoutPlans = (
  params?: GetWorkoutPlansParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetWorkoutPlans200Item[]>(
    { method: 'GET', params, signal, url: `/api/workout-plans/` },
    options,
  );
};

export const getGetWorkoutPlansQueryKey = (params?: GetWorkoutPlansParams) => {
  return [`/api/workout-plans/`, ...(params ? [params] : [])] as const;
};

export const getGetWorkoutPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkoutPlans>>,
  TError = ErrorType<GetWorkoutPlans401 | GetWorkoutPlans500>,
>(
  params?: GetWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkoutPlans>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWorkoutPlansQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutPlans>>> = ({
    signal,
  }) => getWorkoutPlans(params, requestOptions, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkoutPlans>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkoutPlansQueryError = ErrorType<
  GetWorkoutPlans401 | GetWorkoutPlans500
>;
export type GetWorkoutPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutPlans>>
>;

export function useGetWorkoutPlans<
  TData = Awaited<ReturnType<typeof getWorkoutPlans>>,
  TError = ErrorType<GetWorkoutPlans401 | GetWorkoutPlans500>,
>(
  params: GetWorkoutPlansParams | undefined,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkoutPlans>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlans>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlans<
  TData = Awaited<ReturnType<typeof getWorkoutPlans>>,
  TError = ErrorType<GetWorkoutPlans401 | GetWorkoutPlans500>,
>(
  params?: GetWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkoutPlans>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlans>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlans>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlans<
  TData = Awaited<ReturnType<typeof getWorkoutPlans>>,
  TError = ErrorType<GetWorkoutPlans401 | GetWorkoutPlans500>,
>(
  params?: GetWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkoutPlans>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List workout plans
 */
export function useGetWorkoutPlans<
  TData = Awaited<ReturnType<typeof getWorkoutPlans>>,
  TError = ErrorType<GetWorkoutPlans401 | GetWorkoutPlans500>,
>(
  params?: GetWorkoutPlansParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkoutPlans>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkoutPlansQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a workout plan
 */
export const createWorkoutPlan = (
  createWorkoutPlanBody: BodyType<CreateWorkoutPlanBody>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CreateWorkoutPlan201>(
    {
      data: createWorkoutPlanBody,
      headers: { 'Content-Type': 'application/json' },
      method: 'POST',
      signal,
      url: `/api/workout-plans/`,
    },
    options,
  );
};

export const getCreateWorkoutPlanMutationOptions = <
  TError = ErrorType<
    | CreateWorkoutPlan400
    | CreateWorkoutPlan401
    | CreateWorkoutPlan404
    | CreateWorkoutPlan500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWorkoutPlan>>,
    TError,
    { data: BodyType<CreateWorkoutPlanBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWorkoutPlan>>,
  TError,
  { data: BodyType<CreateWorkoutPlanBody> },
  TContext
> => {
  const mutationKey = ['createWorkoutPlan'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWorkoutPlan>>,
    { data: BodyType<CreateWorkoutPlanBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createWorkoutPlan(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWorkoutPlanMutationBody = BodyType<CreateWorkoutPlanBody>;
export type CreateWorkoutPlanMutationError = ErrorType<
  | CreateWorkoutPlan400
  | CreateWorkoutPlan401
  | CreateWorkoutPlan404
  | CreateWorkoutPlan500
>;
export type CreateWorkoutPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWorkoutPlan>>
>;

/**
 * @summary Create a workout plan
 */
export const useCreateWorkoutPlan = <
  TError = ErrorType<
    | CreateWorkoutPlan400
    | CreateWorkoutPlan401
    | CreateWorkoutPlan404
    | CreateWorkoutPlan500
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWorkoutPlan>>,
      TError,
      { data: BodyType<CreateWorkoutPlanBody> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWorkoutPlan>>,
  TError,
  { data: BodyType<CreateWorkoutPlanBody> },
  TContext
> => {
  return useMutation(getCreateWorkoutPlanMutationOptions(options), queryClient);
};

/**
 * @summary Get the active workout plan
 */
export const getActiveWorkoutPlan = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetActiveWorkoutPlan200>(
    { method: 'GET', signal, url: `/api/workout-plans/active` },
    options,
  );
};

export const getGetActiveWorkoutPlanQueryKey = () => {
  return [`/api/workout-plans/active`] as const;
};

export const getGetActiveWorkoutPlanQueryOptions = <
  TData = Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
  TError = ErrorType<
    GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActiveWorkoutPlanQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getActiveWorkoutPlan>>
  > = ({ signal }) => getActiveWorkoutPlan(requestOptions, signal);

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetActiveWorkoutPlanQueryError = ErrorType<
  GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
>;
export type GetActiveWorkoutPlanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getActiveWorkoutPlan>>
>;

export function useGetActiveWorkoutPlan<
  TData = Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
  TError = ErrorType<
    GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getActiveWorkoutPlan>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActiveWorkoutPlan<
  TData = Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
  TError = ErrorType<
    GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getActiveWorkoutPlan>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActiveWorkoutPlan<
  TData = Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
  TError = ErrorType<
    GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the active workout plan
 */
export function useGetActiveWorkoutPlan<
  TData = Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
  TError = ErrorType<
    GetActiveWorkoutPlan401 | GetActiveWorkoutPlan404 | GetActiveWorkoutPlan500
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActiveWorkoutPlan>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetActiveWorkoutPlanQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a workout plan
 */
export const getWorkoutPlan = (
  workoutPlanId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetWorkoutPlan200>(
    { method: 'GET', signal, url: `/api/workout-plans/${workoutPlanId}` },
    options,
  );
};

export const getGetWorkoutPlanQueryKey = (workoutPlanId: string) => {
  return [`/api/workout-plans/${workoutPlanId}`] as const;
};

export const getGetWorkoutPlanQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError = ErrorType<GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500>,
>(
  workoutPlanId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetWorkoutPlanQueryKey(workoutPlanId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutPlan>>> = ({
    signal,
  }) => getWorkoutPlan(workoutPlanId, requestOptions, signal);

  return {
    enabled: !!workoutPlanId,
    queryFn,
    queryKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkoutPlan>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkoutPlanQueryError = ErrorType<
  GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500
>;
export type GetWorkoutPlanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutPlan>>
>;

export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError = ErrorType<GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500>,
>(
  workoutPlanId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError = ErrorType<GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500>,
>(
  workoutPlanId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutPlan>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutPlan>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError = ErrorType<GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500>,
>(
  workoutPlanId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a workout plan
 */
export function useGetWorkoutPlan<
  TData = Awaited<ReturnType<typeof getWorkoutPlan>>,
  TError = ErrorType<GetWorkoutPlan401 | GetWorkoutPlan404 | GetWorkoutPlan500>,
>(
  workoutPlanId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutPlan>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkoutPlanQueryOptions(workoutPlanId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a workout day
 */
export const getWorkoutDay = (
  workoutPlanId: string,
  workoutDayId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetWorkoutDay200>(
    {
      method: 'GET',
      signal,
      url: `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}`,
    },
    options,
  );
};

export const getGetWorkoutDayQueryKey = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return [`/api/workout-plans/${workoutPlanId}/days/${workoutDayId}`] as const;
};

export const getGetWorkoutDayQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError = ErrorType<GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500>,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetWorkoutDayQueryKey(workoutPlanId, workoutDayId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutDay>>> = ({
    signal,
  }) => getWorkoutDay(workoutPlanId, workoutDayId, requestOptions, signal);

  return {
    enabled: !!(workoutPlanId && workoutDayId),
    queryFn,
    queryKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkoutDay>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkoutDayQueryError = ErrorType<
  GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500
>;
export type GetWorkoutDayQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkoutDay>>
>;

export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError = ErrorType<GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500>,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDay>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDay>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError = ErrorType<GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500>,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDay>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDay>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError = ErrorType<GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500>,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a workout day
 */
export function useGetWorkoutDay<
  TData = Awaited<ReturnType<typeof getWorkoutDay>>,
  TError = ErrorType<GetWorkoutDay401 | GetWorkoutDay404 | GetWorkoutDay500>,
>(
  workoutPlanId: string,
  workoutDayId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDay>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkoutDayQueryOptions(
    workoutPlanId,
    workoutDayId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Start a workout session
 */
export const startWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<StartWorkoutSession201>(
    {
      method: 'POST',
      signal,
      url: `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`,
    },
    options,
  );
};

export const getStartWorkoutSessionMutationOptions = <
  TError = ErrorType<
    | StartWorkoutSession401
    | StartWorkoutSession404
    | StartWorkoutSession409
    | StartWorkoutSession422
    | StartWorkoutSession500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startWorkoutSession>>,
    TError,
    { workoutDayId: string; workoutPlanId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof startWorkoutSession>>,
  TError,
  { workoutDayId: string; workoutPlanId: string },
  TContext
> => {
  const mutationKey = ['startWorkoutSession'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startWorkoutSession>>,
    { workoutDayId: string; workoutPlanId: string }
  > = (props) => {
    const { workoutDayId, workoutPlanId } = props ?? {};

    return startWorkoutSession(workoutPlanId, workoutDayId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StartWorkoutSessionMutationError = ErrorType<
  | StartWorkoutSession401
  | StartWorkoutSession404
  | StartWorkoutSession409
  | StartWorkoutSession422
  | StartWorkoutSession500
>;

export type StartWorkoutSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof startWorkoutSession>>
>;

/**
 * @summary Start a workout session
 */
export const useStartWorkoutSession = <
  TError = ErrorType<
    | StartWorkoutSession401
    | StartWorkoutSession404
    | StartWorkoutSession409
    | StartWorkoutSession422
    | StartWorkoutSession500
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startWorkoutSession>>,
      TError,
      { workoutDayId: string; workoutPlanId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startWorkoutSession>>,
  TError,
  { workoutDayId: string; workoutPlanId: string },
  TContext
> => {
  return useMutation(
    getStartWorkoutSessionMutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Complete a workout session
 */
export const completeWorkoutSession = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CompleteWorkoutSession200>(
    {
      method: 'PATCH',
      signal,
      url: `/api/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}/complete`,
    },
    options,
  );
};

export const getCompleteWorkoutSessionMutationOptions = <
  TError = ErrorType<
    | CompleteWorkoutSession401
    | CompleteWorkoutSession404
    | CompleteWorkoutSession500
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeWorkoutSession>>,
    TError,
    { sessionId: string; workoutDayId: string; workoutPlanId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeWorkoutSession>>,
  TError,
  { sessionId: string; workoutDayId: string; workoutPlanId: string },
  TContext
> => {
  const mutationKey = ['completeWorkoutSession'];

  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeWorkoutSession>>,
    { sessionId: string; workoutDayId: string; workoutPlanId: string }
  > = (props) => {
    const { sessionId, workoutDayId, workoutPlanId } = props ?? {};

    return completeWorkoutSession(
      workoutPlanId,
      workoutDayId,
      sessionId,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteWorkoutSessionMutationError = ErrorType<
  | CompleteWorkoutSession401
  | CompleteWorkoutSession404
  | CompleteWorkoutSession500
>;

export type CompleteWorkoutSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeWorkoutSession>>
>;

/**
 * @summary Complete a workout session
 */
export const useCompleteWorkoutSession = <
  TError = ErrorType<
    | CompleteWorkoutSession401
    | CompleteWorkoutSession404
    | CompleteWorkoutSession500
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeWorkoutSession>>,
      TError,
      { sessionId: string; workoutDayId: string; workoutPlanId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof completeWorkoutSession>>,
  TError,
  { sessionId: string; workoutDayId: string; workoutPlanId: string },
  TContext
> => {
  return useMutation(
    getCompleteWorkoutSessionMutationOptions(options),
    queryClient,
  );
};
